[package]
name = "day25-clock_signal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asm_interpreter = { path = "../common/asm_interpreter" }
